### ISSUE TITLE
Propuesta de mejora para el M4

### ISSUE THREAD

**Issue by marjimveg1** [marjimveg1/decideM4#1]
Parte del grupo del subsistema decide-ganamines-almacenamiento van a ir a la mejora que tendrá lugar el próximo 31 de enero de 2019.
Debido a que el subsistema de almacenamiento es complejo y las mejoras que se propusieron requieren bastante tiempo para su implementación y debido al poco tiempo que hay para trabajar en dichas mejoras se puede proponer funcionalidades a otros subsistemas. 
¿Alguna propuesta?

**Comment by marjimveg1** [comment]
@julgargal me parece buena idea, esperamos su contestación.

**Comment by julgargal** [comment]
@marjimveg1 la respuesta ha sido afirmativa, podemos comenzar el M4.
