### ISSUE TITLE
Calcular estadísticas en un método unico

### ISSUE THREAD

**Issue by marjimveg1** [marjimveg1/decideM4#10]
Se considera mejor crear un método en el que solo se calculen las estadíticas, que se almacenen en una lista, diccionario, tupla... y que el método de la vista del dashboard relacionado con la issue #7 solo realialice implementar el template.
¿Te parece buena idea @julgargal ?

**Comment by julgargal** [comment]
De acuerdo

**Comment by marjimveg1** [comment]
He creado una lista heterogénea, de manera que se va haciendo las colsultas y los resultados se almacen en dicha lista. Posteriorme cada uno de los valores de la lista se le pasa a la vista para que sea mostrado en forma de gráfica

**Comment by marjimveg1** [comment]
Ha habido un problema con la estadística de votos por meses, ya que no es posible saber cuando se ha almacenado cada voto. Por esto he decidido cambiar dicha estadística por otra opción, 'Top de las X votaciones más populares'

**Comment by julgargal** [comment]
Haciendo los test he detectado un error en los métodos `numVotacionesSinEmpezar = Voting.objects.filter(start_date=None).count()` y  `numVotacionesActivas = Voting.objects.exclude(start_date=None).count()` , revísalos cuando puedas

**Comment by marjimveg1** [comment]
De acuerdo, ahora mismo lo corrijo @julgargal

**Comment by marjimveg1** [comment]
Arreglado, he modificado estas líneas para que compare fechas en lugar de ver que no "none"
`numVotacionesSinEmpezar = Voting.objects.filter(start_date__gte=datetime.date.today()).count()`

```
 numVotacionesActivas = 0
        for votacion in Voting.objects.all():
            hoy = datetime.date.today()
            if (str(votacion.start_date) <= str(hoy)) and (str(votacion.end_date) >= str(hoy)):
                numVotacionesActivas +=1
```
