### ISSUE TITLE
Despliegue en heroku

### ISSUE THREAD

**Issue by julgargal** [marjimveg1/decideM4#11]
Vamos a realizar el despliegue de Decide, con todas las funcionalidades implementadas en el nuevo subsistema de visualización. 
Para ello seguiremos los pasos que se nos dieron en la Práctica 6, [https://1984.lsi.us.es/wiki-egc/index.php/Despliegue_(Heroku)](url)

**Comment by julgargal** [comment]
Durante el despliegue en Heroku, me ha salido este fallo. Estoy intentando solucionarlo, sabes a qué se debe? 
![image](https://user-images.githubusercontent.com/43671631/51826678-ee298900-22e7-11e9-8fda-76889908daf2.png)

**Comment by marjimveg1** [comment]
https://www.youtube.com/watch?v=zeq4FGSdtTc sigue ese tutorial viene muy bien explicado, le aparee un fallo similar al ese, puede que te ayude

**Comment by marjimveg1** [comment]
¿Puedes enviarme foto del inicio de la traza? @julgargal

**Comment by julgargal** [comment]
Ya está la aplicación desplegada en Heroku, pero como esta no es la versión final y tendremos que actualizar y automatizar el despliegue, dejaremos la issue abierta.

![whatsapp image 2019-01-28 at 11 28 10](https://user-images.githubusercontent.com/43671631/51837424-9dc02480-2303-11e9-9d36-48f77e664a9b.jpeg)

**Comment by julgargal** [comment]
https://decidejulmar2.herokuapp.com/visualizer/sobreNosotros/

Cerramos issue
