### ISSUE TITLE
Test unitarios del sistema

### ISSUE THREAD

**Issue by marjimveg1** [marjimveg1/decideM4#12]
Una vez implementada los métodos se va a prodecer a testear los métodos implementados a traves de test unitarios de las clase tests.py y automatizados con travis.

**Comment by marjimveg1** [comment]
Se ha detectado este fallo cuando se ejecuta travis, ¿alguna idea @julgargal ?
![captura de pantalla de 2019-01-28 13-48-14](https://user-images.githubusercontent.com/36474784/51837502-d95aee80-2303-11e9-872f-685b38ecf42d.png)

**Comment by julgargal** [comment]
Prueba a cambiar el "months" por "days" @marjimveg1

**Comment by marjimveg1** [comment]
De acuerdo, gracias.

**Comment by marjimveg1** [comment]
Era eso, lo subo a master.
![captura de pantalla de 2019-01-28 13-48-14](https://user-images.githubusercontent.com/36474784/51837633-41a9d000-2304-11e9-815f-b4e3debbd4db.png)

**Comment by julgargal** [comment]
De acuerdo, comienzo yo mis test entonces.

**Comment by julgargal** [comment]
Haciendo los test he detectado un error en los métodos `numVotacionesSinEmpezar = Voting.objects.filter(start_date=None).count()` y  `numVotacionesActivas = Voting.objects.exclude(start_date=None).count()` , de `/visualizer/views.py`  revísalos cuando puedas.
