### ISSUE TITLE
Gestión de las comunicaciones.

### ISSUE THREAD

**Issue by julgargal** [marjimveg1/decideM4#2]
Me parece necesario que exista una metodología de comunicaciones definida, por lo que en wiki se ha creado un 'diario de grupo' para que así tengamos registradas todas las tareas realizadas, así como el número de horas invertidas y acordemos que sea en ese documento donde se apunte dicha información. Te dejo el enlace al diario:

[https://github.com/marjimveg1/decideM4/wiki/Diario-de-grupo.](url)

**Comment by marjimveg1** [comment]
Gracias @julgargal .

**Comment by marjimveg1** [comment]
Se puede cerrar esta issue
