### ISSUE TITLE
Implementación de la visualización del menú principal de las votaciones.

### ISSUE THREAD

**Issue by julgargal** [marjimveg1/decideM4#3]
La primera funcionalidad que vamos a implementar para completar este M4 será la implementación de la visualización del menú principal de las votaciones donde crearemos una original interfaz donde se muestren todas las votaciones existentes con el objetivo de poder acceder a ellas de una manera fácil e intuitiva. 

Esta funcionalidad debe completarse entre el día 25 y 26 de enero por lo que será asignada a las dos integrantes del grupo con el fin de acabarla lo antes posible.

**Comment by marjimveg1** [comment]
Me asigno realizar la parte de implementación de los métodos de la clase "views.py". Cuando lo tenga terminado @julgargal puedes darle estilo.

**Comment by marjimveg1** [comment]
La página principal constará de un menú desde donde se podrá redirigir a las distintas funcionalidad del módulo de visualización.

**Comment by julgargal** [comment]
De acuerdo @marjimveg1 espero entonces a que me avises para comenzar entonces con el diseño de dicha vista.

**Comment by julgargal** [comment]
@marjimveg1 revisa el código del índice. Tienes un fallo en los enlaces del índice, por ejemplo pones `<li><a href='/inicio'>Inicio</a></li>` en vez de `<li><a href='/visualizer/inicio'>Inicio</a></li>` .

**Comment by marjimveg1** [comment]
Se ha resuelto el problema añadiendo a la url /visualizer/...

**Comment by marjimveg1** [comment]
@julgargal revisa la funcionalidad y puede darse por cerrada el issue #3

**Comment by julgargal** [comment]
Issue completada.
