### ISSUE TITLE
Implementación listar los resultados de todas las votaciones. 

### ISSUE THREAD

**Issue by julgargal** [marjimveg1/decideM4#4]
Tras haber implementado correctamente el menú principal y la correspondiente visualización de todos sus enlaces, procedemos a realizar la implementación del método "listar resultados de todas las votaciones". Esto será una tabla en la que nos mostrará los resultados obtenidos en cada una de las votaciones finalizadas.

**Comment by marjimveg1** [comment]
@julgargal he mergeado a la master una nueva clase en views.py para que muestre la lista de todos los resultados. Puedes darle estilo.

**Comment by marjimveg1** [comment]
Esta funcionalidad esta implementada, se da por cerrada
