### ISSUE TITLE
Implementar dashboard

### ISSUE THREAD

**Issue by marjimveg1** [marjimveg1/decideM4#7]
Se va a implementar una nueva funcionalidad que será un _dashboard_ en la que el usuario puede en un simple panel varias estadisticas como:

- Número total  de votaciones
- Número de votaciones cerradas
- Número de votaciones sin empezar
-Media de las opciones que se dan por pregunta de la votación

se pueden ir añadiendo otras, pero estas sería la idea inicial.

Además, una vez implementada la funcionalidad, @julgargal se encargará de dar diseño la funcionalidad.

**Comment by julgargal** [comment]
Cerramos issue
